/**
 * Writes supabase/seed.sql from the demonstration inventory.
 *   npm run seed:generate
 *
 * The seed is for LOCAL / STAGING databases only. Every row is flagged
 * is_demo = true and demo accounts have no password, so they cannot sign in.
 * Remove demo data at any time with:  delete from auth.users where email like '%@demo.motionx.invalid';
 */
import { writeFileSync } from "node:fs";
import { join } from "node:path";
import { DEMO_SELLERS, DEMO_VEHICLES, demoPhotos } from "../src/lib/demo/inventory";
import { demoVehicleSlug } from "../src/lib/data/mappers";

const q = (v: unknown): string => {
  if (v === null || v === undefined) return "null";
  if (typeof v === "number") return String(v);
  if (typeof v === "boolean") return v ? "true" : "false";
  return `'${String(v).replace(/'/g, "''")}'`;
};

const lines: string[] = [
  "-- GENERATED by scripts/generate-seed.ts — do not edit by hand.",
  "-- DEMONSTRATION DATA for local/staging databases only. Never run in production.",
  "begin;",
  "",
];

for (const s of DEMO_SELLERS) {
  const meta = JSON.stringify({ display_name: s.displayName, account_type: s.type === "dealer" ? "dealer" : "private_seller" });
  lines.push(
    `insert into auth.users (id, instance_id, aud, role, email, encrypted_password, email_confirmed_at, raw_app_meta_data, raw_user_meta_data, created_at, updated_at)
values (${q(s.id)}, '00000000-0000-0000-0000-000000000000', 'authenticated', 'authenticated', ${q(`demo-${s.key}@demo.motionx.invalid`)}, '', now(), '{"provider":"email","providers":["email"]}', ${q(meta)}::jsonb, '2026-09-01T00:00:00Z', now())
on conflict (id) do nothing;`,
  );
  lines.push(`update public.profiles set is_demo = true, country_code = ${q(s.countryCode)}, city = ${q(s.city)}, created_at = '2026-09-01T00:00:00Z' where id = ${q(s.id)};`);
  if (s.type === "dealer") {
    lines.push(
      `insert into public.dealer_profiles (id, slug, business_name, description, country_code, region, city, created_at)
values (${q(s.id)}, ${q(s.slug)}, ${q(s.displayName)}, ${q(s.description)}, ${q(s.countryCode)}, ${q(s.region)}, ${q(s.city)}, '2026-09-01T00:00:00Z')
on conflict (id) do nothing;`,
    );
  }
  lines.push("");
}

const sellerId = new Map(DEMO_SELLERS.map((s) => [s.key, s.id]));
for (const v of DEMO_VEHICLES) {
  const cols = {
    id: v.id, seller_id: sellerId.get(v.sellerKey), slug: demoVehicleSlug(v), make: v.make, model: v.model, variant: v.variant,
    year: v.year, price: v.price, currency: v.currency, country_code: v.countryCode, region: v.region, city: v.city,
    mileage: v.mileage, mileage_unit: v.mileageUnit, condition: v.condition, body_style: v.bodyStyle, transmission: v.transmission,
    fuel_type: v.fuelType, drivetrain: v.drivetrain, segment: v.segment, exterior_colour: v.exteriorColour,
    interior_colour: v.interiorColour, engine: v.engine, power_hp: v.powerHp, doors: v.doors, seats: v.seats,
    description: v.description, status: v.sold ? "sold" : "active", is_demo: true, featured: Boolean(v.featured),
    inspection_available: Boolean(v.inspectionAvailable), published_at: v.publishedAt, approved_at: v.publishedAt,
    submitted_at: v.publishedAt, created_at: v.publishedAt,
  };
  lines.push(`insert into public.vehicles (${Object.keys(cols).join(", ")})
values (${Object.values(cols).map(q).join(", ")})
on conflict (id) do nothing;`);
  demoPhotos(v).forEach((img, i) => {
    lines.push(`insert into public.vehicle_images (vehicle_id, url, alt, width, height, position) select ${q(v.id)}, ${q(img.src)}, ${q(img.alt)}, ${img.width}, ${img.height}, ${i}
where not exists (select 1 from public.vehicle_images where vehicle_id = ${q(v.id)} and position = ${i});`);
  });
  lines.push("");
}

lines.push("commit;", "");
const out = join(__dirname, "..", "supabase", "seed.sql");
writeFileSync(out, lines.join("\n"));
console.log(`Wrote ${out} (${DEMO_SELLERS.length} demo sellers, ${DEMO_VEHICLES.length} demo vehicles)`);
